In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import math 

from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.metrics import accuracy_score

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFECV

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns

%matplotlib inline
mpl.style.use( 'ggplot' )
sns.set_style( 'white' )
pylab.rcParams[ 'figure.figsize' ] = 8 , 6

In [2]:
df = pd.read_csv("Dataset.csv")

In [3]:
df

,Crop,Jan-21,Feb-21,Mar-21,Apr-21,May-21,Jun-21,Jul-21,Aug-21,Sep-21,Oct-21,Nov-21,Dec-21
0,Rice agric,388.95,395.20,393.25,368.10,443.10,445.21,431.03,455.17,450.50,466.50,416.92,461.18
1,Rice,311.29,312.54,315.60,322.54,375.62,365.52,348.47,372.48,38.13,40.00,37.08,37.06
2,Maize grain,150.43,150.43,184.84,193.35,201.53,209.82,241.07,290.76,347.38,332.00,324.06,359.67
3,Maize,149.32,169.32,194.29,214.96,205.36,219.20,254.46,276.61,311.68,309.41,281.25,305.71
4,Palm oil,564.10,578.46,574.81,575.00,616.19,625.00,681.48,794.12,1037.50,1042.86,1010.00,1065.56
5,Plantain(ripe),210.00,250.00,290.00,302.50,320.59,245.59,250.00,250.00,1325.00,1000.00,1032.14,1156.14
6,Plantain(unripe),216.67,226.67,275.00,286.67,290.00,266.67,274.34,288.89,310.00,304.29,310.00,276.67
7,Vegetable oil,608.15,621.48,628.00,635.00,650.00,733.33,811.11,831.37,282.50,280.22,275.00,280.77
8,Wheat flour,656.25,675.00,685.00,695.50,693.33,717.50,783.33,800.00,314.48,304.60,300.45,469.54
9,Catfish (obokun) fresh,1030.39,1082.54,1119.32,1000.00,905.69,1025.00,1026.11,1186.25,1012.91,1102.00,935.00,822.22
10,Catfish :dried,1999.32,2037.99,2045.16,1933.33,2014.14,1958.62,1880.00,2002.50,1965.38,1980.00,1857.14,1120.00
11,Catfish Smoked,1428.57,1364.29,1300.00,1333.33,1255.10,1300.00,1314.28,1300.00,1279.87,1100.00,1000.00,1000.00
12,Mackerel : frozen,717.98,710.00,766.67,833.33,754.51,741.67,766.67,833.33,771.93,833.33,833.33,909.09
13,"Groundnut oil: 1 bottle, specify bottle",501.48,497.77,490.33,508.51,490.67,497.33,508.44,500.00,497.70,498.07,473.64,536.30
14,Maize grain white sold loose,147.60,158.92,144.29,150.03,161.25,155.95,153.27,156.58,143.96,156.18,136.75,121.03

In [4]:
df.shape

(15, 13)

In [5]:
df.describe()

,Jan-21,Feb-21,Mar-21,Apr-21,May-21,Jun-21,Jul-21,Aug-21,Sep-21,Oct-21,Nov-21,Dec-21
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.0000,15.000000,15.000000
mean,605.366667,615.374000,627.104000,623.476667,625.138667,633.760667,648.270667,689.204000,672.594667,649.9640,614.850667,594.729333
std,527.419721,526.372819,517.935129,490.960768,486.706762,490.792497,476.921841,504.681995,543.427019,517.6558,485.266494,381.577259
min,147.600000,150.430000,144.290000,150.030000,161.250000,155.950000,153.270000,156.580000,38.130000,40.0000,37.080000,37.060000
25%,213.335000,238.335000,282.500000,294.585000,305.295000,256.130000,264.400000,289.825000,310.840000,304.4450,290.850000,293.240000
50%,501.480000,497.770000,490.330000,508.510000,490.670000,497.330000,508.440000,500.000000,450.500000,466.5000,416.920000,469.540000
75%,687.115000,692.500000,725.835000,764.415000,723.920000,737.500000,797.220000,832.350000,1025.205000,1021.4300,967.500000,954.545000
max,1999.320000,2037.990000,2045.160000,1933.330000,2014.140000,1958.620000,1880.000000,2002.500000,1965.380000,1980.0000,1857.140000,1156.140000

In [6]:
X = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
y = df.loc[ df.Crop == "Maize"  , "Jan-21" : "Dec-21" ].to_numpy()

In [7]:
X = np.array(X)

In [8]:
y

array([[149.32, 169.32, 194.29, 214.96, 205.36, 219.2 , 254.46, 276.61,
        311.68, 309.41, 281.25, 305.71]])

In [9]:
y = y.reshape(12, 1)

In [10]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
X = X.reshape(12, 1)

In [12]:
y.shape

(12, 1)

In [13]:
X.shape

(12, 1)

In [14]:
from sklearn import linear_model
from sklearn import tree
from sklearn import svm
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor

reg = svm.SVR(C=0.5 , epsilon=0.01)
reg.fit(X , y )

SVR(C=0.5, epsilon=0.01)

In [15]:
X_test = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
X_test = np.array(X_test)

In [16]:
pred = reg.predict(X_test.reshape(12 , 1))

In [21]:
pred

array([238.0872343 , 237.64385657, 237.29107623, 237.05724533,
       236.9268967 , 236.86557883, 236.84120774, 236.83302003,
       236.8306945 , 236.83013605, 236.83002267, 236.83000321])

In [22]:
Years = ["Jan-22" , "Feb-22" , "Mar-22" , "Apr-22" , "May-22" , "Jun-22" , "Jul-22" , "Aug-22" , "Oct-22" , "Nov-22" , "Dec-22" ]

In [24]:
def calc_pred(Crop):
    X = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    y = df.loc[ df.Crop == Crop , "Jan-21" : "Dec-21" ].to_numpy()
    X = np.array(X)
    y = y.reshape(12 , 1)
    X = X.reshape(12 , 1)
    reg = svm.SVR(C=0.5 , epsilon=0.01)
    reg.fit(X , y ) 
    X_test = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    X_test = np.array(X_test)
    pred = reg.predict(X_test.reshape(12 , 1))
    pred = pred.reshape(12 , 1)
    temp = y.reshape(12 , 1)
    rohit = []
    for i in temp:
        rohit.append(i)
    for i in pred:
        rohit.append(i)
    rohit = np.array(rohit)
    rohit = rohit.reshape(24,)
    Years = ["Jan-22" , "Feb-22" , "Mar-22" , "Apr-22" , "May-22" , "Jun-22" , "Jul-22" , "Aug-22" , "Oct-22" , "Nov-22" , "Dec-22" , "Jan-23" , "Feb-23" , "Mar-23" , "Apr-23" , "May-23" , "Jun-23" , "Jul-23" , "Aug-23" , "Oct-23" , "Nov-23" , "Dec-23" ]
    Years = np.array(Years)
    d = { "Years" : Years , "Prediction" : rohit }
    final = pd.DataFrame(d)
    fig, axes = plt.subplots(1,1)
    fig.set_size_inches(12, 5)
    sns.pointplot(data=final ,x = "Years" ,y = "Prediction", orient="v" )
    fig.savefig("6.png")
    final.to_csv( 'price_predicting.csv' , index = False )
    print(pred)

In [25]:
calc_pred("Maize")

ValueError: All arrays must be of the same length